---
- name: Install and start Apache HTTPD
  hosts: node2
  become: true

  tasks:

    - name: Install httpd package
      ansible.builtin.dnf:
        name: httpd
        state: present

    - name: Start and enable httpd service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

    - name: Allow HTTP service in firewall
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes

    - name: Create a test index.html
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: "Hello from Ansible Navigator!\n"
