---
- name: set_fact demo
  hosts: localhost
  tasks:
    - name: Setting host facts using complex arguments
      ansible.builtin.set_fact:
        myfirstfact: saturday
        mysecondfact: evening
    
    - debug:
       msg: Recording this on {{ myfirstfact }} {{ mysecondfact }}


- name: new play
  hosts: localhost
  tasks: 
    - debug:
        msg: It is still {{ myfirstfact }} {{ mysecondfact }}
